# @format

name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: CDK Deploy
        uses: koboriakira/gh-actions/aws/deploy_cdk@main
        with:
          workdir: cdk
          aws-role: ${{ secrets.AWS_ROLE }}
