# @format

name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: CDK Deploy
        uses: koboriakira/gh-actions/aws/deploy_cdk@main
        with:
          aws-role: ${{ secrets.AWS_ROLE }}
        env:
          SLACK_KOBORI_WORKSPACE_ID: ${{ secrets.SLACK_KOBORI_WORKSPACE_ID }}
          SLACK_KOBORI_NOTICE_CHANNEL_ID: ${{ secrets.SLACK_KOBORI_NOTICE_CHANNEL_ID }}
          COMMON_BUCKET_NAME: ${{ secrets.COMMON_BUCKET_NAME }}
